Features
Fanger53/responsive-design pull request #3
Opened 2020-09-03 18:08 UTC by Fanger53

first pull request of the next web page project

2020-09-03 18:24 UTC, MuriloRoque reviewed
# Status: Invalid :red_circle: 

### Hello @Fanger53 and @ositaadimma :wave: 

### I am marking this project as invalid for the following reasons:

- [ ] Your Pull Request needs to have a meaningful title and message, please edit it so it becomes more professional. You should describe what is the purpose of the project and what you did to complete it :+1: 

- [ ] Your README file should be more professional too, please add a screenshot and format it. You can use [this](https://github.com/microverseinc/readme-template) template if you like :smile: 

### Kindly make the requested changes and submit for another review, please :pray: 

### I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-09-03 18:45 UTC, Fanger53 commented
the readme file was updated  with the screenshots of the project

2020-09-03 19:25 UTC, Spayco requested changes
# Changes Requested 

Hello Team! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

* [ ] Pull Request should have  a meaningful title ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

- [ ] Files not related to the project should not be committed and added to .gitignore (e.g. `package-lock.json`) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

> I Added more required changes below

### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2020-09-03 19:25 UTC, SpaYco commented on README.md
> +Live Demo Link:https://raw.githack.com/Fanger53/responsive-design/tree/features
- [ ] never add something without testing, your demo link doesn't work, you need to use the link for `index.html` not the repo, in order for it to work.

2020-09-03 19:25 UTC, SpaYco commented on README.md
> +Linkedin:
- [ ] if you don't have links, remove this.

2020-09-03 19:25 UTC, Spayco commented on css/media-querys.css
> +  /* nav bar size desktop */
- [ ] desktop size is 1024px

2020-09-03 19:25 UTC, Spayco commented on css/media-querys.css
> +  /* nav-bar */
- [ ] this should be 768px

2020-09-03 19:25 UTC, Spayco commented on index.html
> +              </div>
on large screens: 

- [ ] the small titles should be on the right in one line

| Yours | Original |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/11758151/92156977-ac48b900-ee21-11ea-841a-1012a64df9e2.png) | ![image](https://user-images.githubusercontent.com/11758151/92157018-bc609880-ee21-11ea-8045-0d1a2b6c38e7.png) |

on medium screens: 

- [ ] the small titles should on the same line under the big title, with borders in between

| Yours | Original |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/11758151/92157168-f7fb6280-ee21-11ea-9b4f-0898a264fd76.png) | ![image](https://user-images.githubusercontent.com/11758151/92157203-06497e80-ee22-11ea-8d18-731cf55cd697.png) |

2020-09-03 19:25 UTC, Spayco commented on index.html
> +            </div>
- [ ] change the colors of the links

| Yours | Original |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/11758151/92157404-41e44880-ee22-11ea-8e18-668ff1e3876f.png) | ![image](https://user-images.githubusercontent.com/11758151/92157439-4f013780-ee22-11ea-9458-ce0ffd118add.png) |

2020-09-03 19:25 UTC, Spayco commented on index.html
> +        </div>
- [ ] these should be in one line on both large and medium screens, and 3 lines on small screens, yours changes on the medium screen

2020-09-03 19:25 UTC, Spayco commented on index.html
> +            <li class="list-li"><a href="#" class="footer-list-a">CONTACT</a></li>
- [ ] the contact icon goes to the next line on small screens
![image](https://user-images.githubusercontent.com/11758151/92158066-3fceb980-ee23-11ea-84b7-9620322fd4eb.png)

2020-09-03 21:10 UTC, MuriloRoque requested changes
# Changes requested :red_circle: 

### Hello again @Fanger53 and @ositaadimma :wave: 

### Nice job implementing most of the changes requested by the previous TSE, but we need to fix one thing that was left behind after his review:

- [x] **(MANDATORY)** Your footer links are still going above each other, check the screenshots below for medium and small screens:

![Screenshot from 2020-09-03 17-59-39](https://user-images.githubusercontent.com/59691171/92166955-ed37d200-ee0f-11ea-946e-cc5aaf8c05b9.png)
<br>
![Screenshot from 2020-09-03 17-59-36](https://user-images.githubusercontent.com/59691171/92166970-f32db300-ee0f-11ea-8ac6-a3dc56089e75.png)
<br>

### The next suggestions are marked as **OPTIONAL**, since they weren't requested by the previous TSE:

- [ ] **(OPTIONAL)** On large screens, your page is not centered, it's not covering the entire width, like in the original:

![Screenshot from 2020-09-03 17-58-35](https://user-images.githubusercontent.com/59691171/92167074-283a0580-ee10-11ea-819d-46f22bd913d0.png)
<br>

- [ ] **(OPTIONAL)** There should be a TNW logo inside of this big image at the top of the page, below the navbar, please check the original:

![Screenshot from 2020-09-03 17-59-01](https://user-images.githubusercontent.com/59691171/92167138-44d63d80-ee10-11ea-96e5-6d1118d006fe.png)
<br>

- [ ] **(OPTIONAL)** On very small screens, the content of your page doesn't fit the outer container, since this container gets too small, see below:

![Screenshot from 2020-09-03 17-59-46](https://user-images.githubusercontent.com/59691171/92167270-7f3fda80-ee10-11ea-91ea-30ad1b667f80.png)
<br>

- [ ] **(OPTIONAL)** You are using a lot of repeated properties in your CSS (check below), please make classes for these properties, so your file can be more professional and organized :smiley: 

 12 |   color: white;
      10 |   font-weight: 700;
       9 |   width: 100%;
       8 |   align-items: center;
       7 |   width: 95%;
       6 |   color: black;
       6 |   display: grid;
       5 |   color: red;
       5 |   display: inline-block;
       5 |   display: none;
       5 |   justify-content: space-between;

### Kindly make the requested changes and submit for another review, please :pray: 

### I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-09-03 22:47 UTC, Spayco requested changes
# Changes Requested 

Hello Team! 👋 
Awesome job so far!! 👍 you still need to make a few more changes!

## Required Changes ♻️ 

- [ ] on small screens the content of the page is taking more than the screen, make it always take 100% of the screen 
![image](https://user-images.githubusercontent.com/11758151/92180679-86caa800-ee3f-11ea-9557-06a7d723eb2a.png)

- [ ] the search button on the navbar should be on the very right at the medium screen, on small screens,
 it should be with a hamburger.
 they exist but they are not on the right, if I widen the screen it will have a space on the side, and if I shrink it, the buttons will go inside the screen

![image](https://user-images.githubusercontent.com/11758151/92180788-cabdad00-ee3f-11ea-8542-87f11eb92512.png)
![image](https://user-images.githubusercontent.com/11758151/92180810-d4dfab80-ee3f-11ea-8df8-5e7b85d21a1d.png)

### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2020-09-04 16:19 UTC, MuriloRoque approved these changes
# Status: Approved :green_circle: 

### Hello again @Fanger53 and @ositaadimma :wave: 

### Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-09-04 19:30 UTC, merged